language: node_js
node_js:
- '6'
before_install:
- npm i npm-cli-login -g
- echo "NPM_USER=${NPM_USER}"
- npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
install:
- npm install
script:
- ./ci/build.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
- ./ci/travis/push_sugos_index.js

env:
  secure: "BRCfHeom8JmXcyK2LbVyDVjekdHN1992eZT5WZUfO5DsGelP7SwHO+xU0W8JqlyVruILGz9fKbmtAl2kFner0XHWdUUN3zOLa5I3DbjEmhfMYKPWMfFk43YacD5KX8UObbmQ/eFnsjOuNWVss+PruOmU528ScUyfQigMZA5MBKThXjIgQ1hKYqaXbTAANzWTD4Gw/nw4DOA70Yjg/UXBIKE/j/pwHZDYLZQ5jDg1qnmKwrsJN8IJEevHPbunIHUkvJPWXCg4/+OAlXV88kYtZy8W4JUha/GmeLwxQe0tU7GuYTFEzdD7xIaUCHlsPMCWfmJFYDnwMueqfaGbpqypRbw+DjqfT3IFeafVjZMSv2PtNQYy76TIm0i1Sk0ms6xFcZ40kl1tW/CQROrK40xCRWp5MWargR4/+4jeGaxDwv5jFfTQ//76nI2VatcpfHJkrc2wjn83Bemk8HLDde03P0i/9kdj56DirRfCIeTxboz8fN0wUwwsnkXj/DxPjzPmjCmigu9qU9JLLkUl7u3o89Bbeg5qgR50xjV1RptdhC3Yy4kv5A3ENpjdpX0VajL9nB8bmRa/ZT7T4jTAwdOC5m6dbuzSUCCLKb6i9mKpWYtuwgEi2Fs3ja/VJKU/AFHZw08xpGyttlUp3vnn9NWGOkRcdkpvIzWHWZBQYWasyc4="